# Generated by Django 4.2.5 on 2023-09-24 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolistitem',
            name='day',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
